# Site settings
title: CrispyBits.io
email: admin@crispybits.io
description: Tasty nuggest of technical goodness, half-baked to perfection
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://crispybits.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - node_modules
  - package.json
  - package-lock.json
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Keep these site files when Jekyll runs since they're created by Gulp.
keep_files:
  - css
  - scripts
